### ISSUE TITLE
Browser back button not working all the way

### ISSUE THREAD

**Issue by aleksblendwerk** [Kreyu/data-table-bundle#125]
First of all, thank you for this great library, looks very promising!

I came across a problem in my tests though. 

I start my journey at `/books/` where I use this bundle to display a data table of Book entities. 
In my browser, this URL gets rewritten to `/books?page_book=1&limit_book=25` instantly, which I guess is how it works.

Then I click on the pagination page number links to visit

`/books?page_book=2&limit_book=25`
`/books?page_book=3&limit_book=25`
`/books?page_book=4&limit_book=25`
`/books?page_book=5&limit_book=25`

which works just fine - the new pages with new content are loaded, the active page highlighting in the pagination changes and all.

Now when I click the browser back button, it works fine up to

`/books?page_book=2&limit_book=25`

But when I click the browser back button again on this page (2), the URL changes to `/books?page_book=1&limit_book=25` but I am still seeing the contents of page 2.

Did I forget to set something up or is my main HTML layout missing anything Turbo-related maybe?

**Comment by Kreyu** [comment]
Hey, thanks for the report. I'll try to reproduce it soon and check what's causing the issue

**Comment by Kreyu** [comment]
Yeah, you're right, the back/forward navigation seems broken, as it does not refresh the turbo frame. I am not _yet_ sure if it's an issue with the theme HTML in the bundle, or whether the Hotwire Turbo requires additional configuration to make it work properly

**Comment by Kreyu** [comment]
There were multiple factors that caused this error by the bundle. Should be fixed on the main branch for now, I'll draft a version 0.25 soon (I hope today or tomorrow) after fixing an issue with duplicate queries.

**Comment by Kreyu** [comment]
Should be fixed in 0.25.0

**Comment by ErnadoO** [comment]
Hi @Kreyu,

Thank you for your amazing work!

However, I still have the same issue as @aleksblendwerk with the latest version, so I’m sticking with v0.19.2 for now.

I can reproduce this bug even with a basic setup using the [Symfony demo](https://github.com/symfony/demo) project, symfony/ux-turbo, and your bundle.

Thanks again for your work!

**Comment by Kreyu** [comment]
Thanks for the report @ErnadoO, I'll look into it again

**Comment by Kreyu** [comment]
The back button wasn't working properly if first page was displayed without query parameters. Then, `state` Stimulus controller was changing the URL to include all the data table related query params (pagination, filters, etc.):

https://github.com/Kreyu/data-table-bundle/blob/677bbab6515056e938c5167433c69843c72af23a/assets/controllers/state.js#L24-L26

Now, the back button wasn't working properly, because simply updating the window history is not enough - Turbo loses track of it. Turbo's navigator history has be updated as well:

https://github.com/Kreyu/data-table-bundle/blob/102a326c33c5be7266f21e34a7df0cc01c91f82e/assets/controllers/state.js#L24-L27

Fixed in v0.25.6. Thanks again for the report @ErnadoO.

**Comment by ErnadoO** [comment]
Hi @Kreyu !

Thank you for watching. I just tested v25.6, and this bug seems to be fixed, so thank you very much!
